### ISSUE TITLE
In results tables, break long tournament names onto 2 lines

### ISSUE THREAD

**Issue by tehh4ck3r** [Liquipedia/flow#1]
http://wiki.teamliquid.net/dota2/Team_Liquid/Results
![image](https://cloud.githubusercontent.com/assets/2187346/21077740/ced8fe2c-bf12-11e6-81ed-a9328b24d69e.png)

Break the long tournament name "StarLadder i-League StarSeries Season 1: Europe and CIS Last Chance Qualifier" onto 2 lines so the results table fits without having to scroll

**Comment by FO-nTTaX** [comment]
https://github.com/Liquipedia/flow/commit/b4eea493b40134b045aae4697230734e5ea758cd resolves this
