### ISSUE TITLE
array_merge

### ISSUE THREAD

**Issue by jcmanolong21** [Liquipedia/flow#12]
I have errors when I cloned this and used this skin in to my mediawiki. v1.33

it says that:

Warning: array_merge(): Argument #1 is not an array in C:\xampp\htdocs\southmedia\dota2\skins\LiquiFlow\LiquiFlowHooks.php on line 29

Fatal error: Uncaught Error: Call to undefined method OutputPage::addModuleScripts() in C:\xampp\htdocs\southmedia\dota2\skins\LiquiFlow\SkinLiquiFlow.php:37 Stack trace: #0 C:\xampp\htdocs\southmedia\dota2\includes\skins\SkinTemplate.php(227): Liquipedia\LiquiFlow\Skin->initPage(Object(OutputPage)) #1 C:\xampp\htdocs\southmedia\dota2\includes\OutputPage.php(2723): SkinTemplate->outputPage() #2 C:\xampp\htdocs\southmedia\dota2\includes\exception\MWExceptionRenderer.php(134): OutputPage->output() #3 C:\xampp\htdocs\southmedia\dota2\includes\exception\MWExceptionRenderer.php(53): MWExceptionRenderer::reportHTML(Object(Error)) #4 C:\xampp\htdocs\southmedia\dota2\includes\exception\MWExceptionHandler.php(98): MWExceptionRenderer::output(Object(Error), 2) #5 C:\xampp\htdocs\southmedia\dota2\includes\exception\MWExceptionHandler.php(172): MWExceptionHandler::report(Object(Error)) #6 C:\xampp\htdocs\southmedia\dota2\includes\exception\MWExceptionHandler.php(144): MWExceptionHandler::handleException(Object(Error)) #7 [internal fu in C:\xampp\htdocs\southmedia\dota2\skins\LiquiFlow\SkinLiquiFlow.php on line 37

**Comment by FO-nTTaX** [comment]
Hello, 

This MediaWiki skin currently only supports the 1.31 LTS MediaWiki version (the version we use ourselves). Since we are phasing out its use in favour of a new skin on Liquipedia (and thus are not going to work on compatibility with newer MediaWiki versions) and since I can't support a competing Dota2 wiki, I can unfortunately not help you with this.

**Comment by jcmanolong21** [comment]
Hi, thanks for the information. Is it okay if I ask you about how to deal
with the templates? I have been having troubles understanding the flow of
mediawiki's templates. Also, I have already installed/cloned all of
Liquipedia's extensions. But it seems that the output really is not the
exact same I was expecting, do you mind checking out my question on
stackoverflow? If you may, I badly need this for my project
https://stackoverflow.com/questions/58534833/mediawiki-templates

Thank you for your reply.

**Comment by FO-nTTaX** [comment]
It seems like I answered that question on stackoverflow, this issue doesn't seem like the correct place for this question.

You will not be able to 100% replicate the Liquipedia setup though, as not all of our extensions are publicly available.

Good Luck.
