### ISSUE TITLE
Uncaught:ConfigException

### ISSUE THREAD

**Issue by jcmanolong21** [Liquipedia/flow#13]
Hi, I just installed Wikimedia version 1.31.5 but I'm still getting the same errors. the error says:

MediaWiki internal error.
Fatal error: Uncaught ConfigException: GlobalVarConfig::get: undefined option: 'LiquiFlowAlphawiki = LiquiFlowAlphawiki' in C:\xampp\htdocs\samplemedia\includes\config\GlobalVarConfig.php:53

And this is the code on line 53:
throw new ConfigException( __METHOD__ . ": undefined option: '$name'" );
(public function get( $name = 'LiquiFlowAlphawiki') {
		if ( !$this->has( $name ) ) {
			throw new ConfigException( __METHOD__ . ": undefined option: '$name'" );
		}
		return $this->getWithPrefix( $this->prefix, $name );
	}
)

**Comment by FO-nTTaX** [comment]
It's an undefined variable, set it in your LocalSettings.php file like `$wgLiquiFlowAlphawiki = false;`
