### ISSUE TITLE
Is this skin still maintained?

### ISSUE THREAD

**Issue by jdlrobson** [Liquipedia/flow#16]
The skin has various problems when I try to use it on the current master of MediaWiki. I was wondering if a patch would be accepted to fix this?

**Comment by FO-nTTaX** [comment]
Please see https://github.com/Liquipedia/LiquiFlow/issues/15#issuecomment-756864038

**Comment by jdlrobson** [comment]
Sorry my bad I asked that alreary. Perhaps something the repo could be archived or a note added to the READMe?

**Comment by FO-nTTaX** [comment]
Yeah I was planning to archive the repo, however we only updated our wiki to 1.35.3 on Tuesday, and I did not want to archive the repo as long as we still had the skin installed ourselves.

**Comment by jdlrobson** [comment]
Makes sense. Sorry for the confusion. I'm in the process of deprecating lots of code and am trying not to break skins and this one is coming up in my searches but it's not always clear what the skin status is.
