### ISSUE TITLE
Special:Browse issues with respecting fixed width

### ISSUE THREAD

**Issue by tehh4ck3r** [Liquipedia/flow#2]
http://wiki.teamliquid.net/dota2/Special:Browse/SQreen%27s_Squad

Properties that link here section does not respect fixed width: 
![image](https://cloud.githubusercontent.com/assets/2187346/21869060/95359476-d80a-11e6-82b4-25a90a3e31aa.png)

Also, can we increase the width of the leftmost column so the properties don't have linebreaks in awkward places: 
![image](https://cloud.githubusercontent.com/assets/2187346/21869092/bd5f555e-d80a-11e6-9cff-a4f0d6712ba3.png)

**Comment by FO-nTTaX** [comment]
https://github.com/Liquipedia/flow/commit/d8097ba0869853b969ab864c1bfba51059bebbdc this resolves it

**Comment by FO-nTTaX** [comment]
resolved
