### ISSUE TITLE
Add a badge to "Other wikis" in sidebar when page uses Liquipedia links template on mobile 

### ISSUE THREAD

**Issue by tehh4ck3r** [Liquipedia/flow#3]
![img_0462](https://cloud.githubusercontent.com/assets/2187346/22521061/8d6db446-e86b-11e6-8650-e96f95bb3224.PNG)

**Comment by tehh4ck3r** [comment]
After further investigation, make the other wikis links work the same way, where they take you to that same page on the appropriate wiki

**Comment by Clubfan22** [comment]
It should now work the same as on desktop, might take a day or two to be propagated through cache.

**Comment by Clubfan22** [comment]
![mobile_liquipedia_links](https://cloud.githubusercontent.com/assets/837698/22659097/a983d1b2-ec9c-11e6-8817-02a2db498845.png)

Feel free to adjust it if I missed something.
